### ISSUE TITLE
VST folder doesn't exist

### ISSUE THREAD

**Issue by bryan-pardo** [audacitorch/HARP#101]
Julia B.  just installed Reaper 7.09 and it apparently didn't create a VST folder. In any event, the HARP installer's link to the VST folder turns up nothing on her machine. So you can't drag HARP to that location.  Since neither of us knows what the right path to VST plugins is, we can't simply create the folder ourselves. We won't be alone in this

**Comment by cwitkowitz** [comment]
I think the following line is not actually run on the local machine, meaning we only have a symbolic link in the DMG.
https://github.com/audacitorch/HARP/blob/a19f88af002bd7c78e66faf0dced6d5910ee277a/packaging/package.sh#L44

Therefore, if the directory doesn't already exist, it would cause an error.
