### ISSUE TITLE
Windows version of harp missing binaries

### ISSUE THREAD

**Issue by rc2000123** [audacitorch/HARP#116]
During my testing for the windows build. I got errors regarding missing dlls namely:

VCRuntime 140-1.dll
ucrtbased.dll
MSVCP140d.dll
VCRUNTIME140.dll

However from testing, these were all resolved after I installed the windows visual studio 11 SDK

**Comment by xribene** [comment]
Fixed in 9c996c8903c0d52374f858b9260f3a14e2256ce2
