### ISSUE TITLE
Harp errors out when "process" button is hit. 

### ISSUE THREAD

**Issue by bryan-pardo** [audacitorch/HARP#55]
I got the latest HARP VST3 plugin downloaded and installed with Reaper.   I tried two different Gradio endpoints. I got the same error message with both endpoints. These endpoints were:

hugggof/pitch_shifter
descript/vampnet

HERE IS AN IMAGE OF THE REPORTED ERROR
<img width="1046" alt="processing-error" src="https://github.com/audacitorch/HARP/assets/26678616/998050c9-c80e-4c41-8371-bd98e1ed3b3a">

HERE IS THE LOG RETURNED BY HARP AFTER VAMPNET ERRORED OUT
[vamp_net_HARP.log](https://github.com/audacitorch/HARP/files/13030227/vamp_net_HARP.log)

HERE IS THE LOG FOR THE PITCH SHIFTER 
[pitch_shifter_HARP.log](https://github.com/audacitorch/HARP/files/13030216/pitch_shifter_HARP.log)

**Comment by bryan-pardo** [comment]
Note: I couldn't select any audio in the waveform so I just hit "process".  Is that the reason? If so, there should be a much more graceful exit. Something like a message saying "Select audio from the waveform before processing"

**Comment by hugofloresgarcia** [comment]
There's no selection in harp, so there is likely another issue happening here.

**Comment by hugofloresgarcia** [comment]
maybe related to #59
