### ISSUE TITLE
Can't select audio in the waveform + bad hover-over text

### ISSUE THREAD

**Issue by bryan-pardo** [audacitorch/HARP#56]
I don't know if HARP is supposed to operate on the entire waveform in the HARP window, but I was unable to select audio. I can click on it and momentarily see a red box around the mouse pointer. When I drag, though, the box doesn't change shape. If I release the button, the box goes away. Double-clicking doesn't seem to do anything

There is some  hover-over text that happens if I let the mouse pointer sit on the waveform for a bit. It is bad English and I don't know what it is trying to say.  Maybe they are instructions for how to select a portion of the waveform?

<img width="1046" alt="bad-hover-over-text" src="https://github.com/audacitorch/HARP/assets/26678616/0b8da1a4-c4ee-46a6-ac5e-11517be8bb41">

**Comment by hugofloresgarcia** [comment]
hover over text: #49
