### ISSUE TITLE
when you reopen a plugin with an interface loaded, the space textbox should STILL be populated with the current space. 

### ISSUE THREAD

**Issue by hugofloresgarcia** [audacitorch/HARP#58]
otherwise it crashes

**Comment by hugofloresgarcia** [comment]
(only happens after you do a clean restart of reaper)

**Comment by hugofloresgarcia** [comment]
to repro: 

1. open HARP on a clean project
2. load an HF space by typing it into the bar and hitting load
3. (the model loads, the controls pop up)
4. close the UI for the plugin
5. open the UI again
6. the controls are still there, but the textbox is empty
7. when you hit process (with the textbox empty), it should crash (even though the controls are there)

**Comment by xribene** [comment]
Can't reproduce step 7. It still processes successfully even though the textbox shows "path to a gradio  endpoint"
