### ISSUE TITLE
Ability to use hotkeys in HARP.

### ISSUE THREAD

**Issue by cwitkowitz** [audacitorch/HARP#63]
Currently, there is no support for hotkeys within HARP:
- ENTER (load button)
- CTRL+C
- CTRL+V

If these were supported, it would greatly improve usability of the plugin.

**Comment by cwitkowitz** [comment]
CTRL+A would also be nice!

**Comment by xribene** [comment]
CTRL + {A, C, V} work fine in windows10. Using Enter to 'load' the model can be added

**Comment by cwitkowitz** [comment]
Added support for ENTER key in https://github.com/audacitorch/HARP/pull/82.

**Comment by cwitkowitz** [comment]
One simple workaround is to make sure "Send all keyboard input to plug-in" under the "FX" window is selected. See https://forum.juce.com/t/reaper-stealing-spacebar-keystrokes-in-texteditor/30689 for more information.
