### ISSUE TITLE
add a glossary/index of models that users can load

### ISSUE THREAD

**Issue by hugofloresgarcia** [audacitorch/HARP#74]

**Comment by hugofloresgarcia** [comment]
@cwitkowitz would you be down to take this on?

**Comment by cwitkowitz** [comment]
I actually already added the following to our meeting notes:

Index of models//HF spaces:
- hugggof/pitch_shifter (https://huggingface.co/spaces/hugggof/pitch_shifter)
- hugggof/harmonic_percussive (https://huggingface.co/spaces/hugggof/harmonic_percussive)
- hugggof/MusicGen (https://huggingface.co/spaces/hugggof/MusicGen)
- descript/vampnet (https://huggingface.co/spaces/descript/vampnet)
- cwitkowitz/timbre-trap (https://huggingface.co/spaces/cwitkowitz/timbre-trap)

Do we want this information on the actual plugin or in a specific location (e.g. README)?

**Comment by hugofloresgarcia** [comment]
I think the easiest way for now is to put it into the README or small website (maybe a good time to setup audacitorch.github.io?), then add a link to it from inside the plugin. If you wanna add the link to it from within the plugin, then you'll prob add most of the logic to ProcessorEditor.cpp/.h

**Comment by hugofloresgarcia** [comment]
also we should pay to run Musicgen on a GPU huh

**Comment by cwitkowitz** [comment]
Addressed by https://github.com/audacitorch/HARP/pull/82. I'll open a separate issue for a website, since that seems like a more significant undertaking.
