### ISSUE TITLE
waveform doesn't update when processing is done

### ISSUE THREAD

**Issue by bryan-pardo** [audacitorch/HARP#91]
When you hit "process" you get a text that says "status.PROCESSING" and then this changes to "status.FINISHED"...but the new waveform doesn't appear until you hit the spacebar or click on the waveform. The waveform should updated when the processing is finished.

**Comment by xribene** [comment]
Does anyone else have reproduce this problem ? Even though I don't have it in Windows, I might know why this is happening.
