### ISSUE TITLE
Issues witht wrong waveform thumbnail for processed audio

### ISSUE THREAD

**Issue by xribene** [audacitorch/HARP#93]
3 audio files, at 22k, 44k and 48k. Exactly the same content and processing. Only the 44k waveform is displayed correctly.

![image](https://github.com/audacitorch/HARP/assets/15819935/35b60a5f-03b0-43e5-a0ba-80607938e9a5)

**Comment by hugofloresgarcia** [comment]
from #94 it seems like even though only one region is processed, all of the waveforms are changed in the UI. 

to repro:

Create a single Playback Region by importing a track.
Split that playback region into multiple regions in the DAW
select only one of them, hit process with vampnet with the default controls (unconditional)
result: all of the playback regions should now show a different waveform.
